# Generated by Django 5.2.2 on 2025-07-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('consumption_kwh', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ElectricityUsage',
        ),
    ]
