# Generated by Django 5.2.2 on 2025-07-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_monthlyusage_delete_hourlyusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('energy_mwh', models.FloatField()),
            ],
        ),
    ]
