# Generated by Django 5.2.2 on 2025-07-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_yearlyusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyusage',
            old_name='consumption_kwh',
            new_name='consumption',
        ),
    ]
